### ISSUE TITLE
Question - text_request with session id?

### ISSUE THREAD

**Issue by 21stChannel** [api-ai/apiai-ruby-client#17]
Hi,

I have a question is that how can I make a text request with a session id to distinguish users? I have  created a singleton client instance like:
```
require 'singleton'
class someClass
  include Singleton
  def initialize
    @client = ApiAiRuby::Client.new(
    client_access_token: 'token'
    )
  end
  def client
    return @client
  end
end
```
Then I make a request with the session id of a user:
```
response = Someclass.instance.client.text_request 'request', sessionId: session[:user_id]
```
To test it, I've made an intent which consists of 3 levels of FAQ. But according to the responses, the Bot did not distinguish different users and conversations (for the same intent) from different users interfered with each other. Did I send the request in a wrong way? Or do I have to create a client instance with the session id per user? Thanks in advance.

**Comment by lukeasrodgers** [comment]
@21stChannel looks like from https://github.com/api-ai/apiai-ruby-client/blob/b02a8f7d7a41eff27304674e27e3ee2af92bb9cd/lib/api-ai-ruby/request/request_query.rb that `sessionId` is not extracted from `options`, it comes from `client.api_session_id`. So you'd have to set it on the client before each request, or open a PR -- reading it from `options` looks like it would be easy and not break backwards compat.

**Comment by 21stChannel** [comment]
@lukeasrodgers Thanks for the link :) I will try to change my design base on that.
